version: "3.1"
services:
  api:
    build: .
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOSTNAME="127.0.0.1"
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=GOChat
      - DATABASE_USERNAME=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=GOChat
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: